"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _clubs_list from './clubs-list.bones.json'

configureBoneyard({"animate":"shimmer","speed":"1.5s","stagger":60,"transition":200})

registerBones({
  "clubs-list": _clubs_list,
})
