/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as SignupRouteImport } from './app/routes/signup'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as AuthedRouteImport } from './app/routes/_authed'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthedSchoolsRouteImport } from './app/routes/_authed.schools'
import { Route as AuthedProfileRouteImport } from './app/routes/_authed.profile'
import { Route as AuthedEventsRouteImport } from './app/routes/_authed.events'
import { Route as AuthedClubsRouteImport } from './app/routes/_authed.clubs'
import { Route as AuthedAdminRouteImport } from './app/routes/_authed.admin'
import { Route as AuthedSchoolsIndexRouteImport } from './app/routes/_authed.schools.index'
import { Route as AuthedEventsIndexRouteImport } from './app/routes/_authed.events.index'
import { Route as AuthedClubsIndexRouteImport } from './app/routes/_authed.clubs.index'
import { Route as AuthedAdminIndexRouteImport } from './app/routes/_authed.admin.index'
import { Route as AuthedEventsNewRouteImport } from './app/routes/_authed.events.new'
import { Route as AuthedEventsEventIdRouteImport } from './app/routes/_authed.events.$eventId'
import { Route as AuthedClubsNewRouteImport } from './app/routes/_authed.clubs.new'
import { Route as AuthedClubsClubIdRouteImport } from './app/routes/_authed.clubs.$clubId'
import { Route as AuthedAdminClubsRouteImport } from './app/routes/_authed.admin.clubs'
import { Route as AuthedEventsEventIdIndexRouteImport } from './app/routes/_authed.events.$eventId.index'
import { Route as AuthedClubsClubIdIndexRouteImport } from './app/routes/_authed.clubs.$clubId.index'
import { Route as AuthedSchoolsSchoolIdBoardRouteImport } from './app/routes/_authed.schools.$schoolId.board'
import { Route as AuthedEventsEventIdWizardRouteImport } from './app/routes/_authed.events.$eventId.wizard'
import { Route as AuthedEventsEventIdChatRouteImport } from './app/routes/_authed.events.$eventId.chat'
import { Route as AuthedEventsEventIdBoardRouteImport } from './app/routes/_authed.events.$eventId.board'
import { Route as AuthedClubsClubIdBoardRouteImport } from './app/routes/_authed.clubs.$clubId.board'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSchoolsRoute = AuthedSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEventsRoute = AuthedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClubsRoute = AuthedClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSchoolsIndexRoute = AuthedSchoolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSchoolsRoute,
} as any)
const AuthedEventsIndexRoute = AuthedEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedEventsRoute,
} as any)
const AuthedClubsIndexRoute = AuthedClubsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedClubsRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedEventsNewRoute = AuthedEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedEventsRoute,
} as any)
const AuthedEventsEventIdRoute = AuthedEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AuthedEventsRoute,
} as any)
const AuthedClubsNewRoute = AuthedClubsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedClubsRoute,
} as any)
const AuthedClubsClubIdRoute = AuthedClubsClubIdRouteImport.update({
  id: '/$clubId',
  path: '/$clubId',
  getParentRoute: () => AuthedClubsRoute,
} as any)
const AuthedAdminClubsRoute = AuthedAdminClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedEventsEventIdIndexRoute =
  AuthedEventsEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEventsEventIdRoute,
  } as any)
const AuthedClubsClubIdIndexRoute = AuthedClubsClubIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedClubsClubIdRoute,
} as any)
const AuthedSchoolsSchoolIdBoardRoute =
  AuthedSchoolsSchoolIdBoardRouteImport.update({
    id: '/$schoolId/board',
    path: '/$schoolId/board',
    getParentRoute: () => AuthedSchoolsRoute,
  } as any)
const AuthedEventsEventIdWizardRoute =
  AuthedEventsEventIdWizardRouteImport.update({
    id: '/wizard',
    path: '/wizard',
    getParentRoute: () => AuthedEventsEventIdRoute,
  } as any)
const AuthedEventsEventIdChatRoute = AuthedEventsEventIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedEventsEventIdRoute,
} as any)
const AuthedEventsEventIdBoardRoute =
  AuthedEventsEventIdBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AuthedEventsEventIdRoute,
  } as any)
const AuthedClubsClubIdBoardRoute = AuthedClubsClubIdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthedClubsClubIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/clubs': typeof AuthedClubsRouteWithChildren
  '/events': typeof AuthedEventsRouteWithChildren
  '/profile': typeof AuthedProfileRoute
  '/schools': typeof AuthedSchoolsRouteWithChildren
  '/admin/clubs': typeof AuthedAdminClubsRoute
  '/clubs/$clubId': typeof AuthedClubsClubIdRouteWithChildren
  '/clubs/new': typeof AuthedClubsNewRoute
  '/events/$eventId': typeof AuthedEventsEventIdRouteWithChildren
  '/events/new': typeof AuthedEventsNewRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/clubs/': typeof AuthedClubsIndexRoute
  '/events/': typeof AuthedEventsIndexRoute
  '/schools/': typeof AuthedSchoolsIndexRoute
  '/clubs/$clubId/board': typeof AuthedClubsClubIdBoardRoute
  '/events/$eventId/board': typeof AuthedEventsEventIdBoardRoute
  '/events/$eventId/chat': typeof AuthedEventsEventIdChatRoute
  '/events/$eventId/wizard': typeof AuthedEventsEventIdWizardRoute
  '/schools/$schoolId/board': typeof AuthedSchoolsSchoolIdBoardRoute
  '/clubs/$clubId/': typeof AuthedClubsClubIdIndexRoute
  '/events/$eventId/': typeof AuthedEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthedProfileRoute
  '/admin/clubs': typeof AuthedAdminClubsRoute
  '/clubs/new': typeof AuthedClubsNewRoute
  '/events/new': typeof AuthedEventsNewRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/clubs': typeof AuthedClubsIndexRoute
  '/events': typeof AuthedEventsIndexRoute
  '/schools': typeof AuthedSchoolsIndexRoute
  '/clubs/$clubId/board': typeof AuthedClubsClubIdBoardRoute
  '/events/$eventId/board': typeof AuthedEventsEventIdBoardRoute
  '/events/$eventId/chat': typeof AuthedEventsEventIdChatRoute
  '/events/$eventId/wizard': typeof AuthedEventsEventIdWizardRoute
  '/schools/$schoolId/board': typeof AuthedSchoolsSchoolIdBoardRoute
  '/clubs/$clubId': typeof AuthedClubsClubIdIndexRoute
  '/events/$eventId': typeof AuthedEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/clubs': typeof AuthedClubsRouteWithChildren
  '/_authed/events': typeof AuthedEventsRouteWithChildren
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/schools': typeof AuthedSchoolsRouteWithChildren
  '/_authed/admin/clubs': typeof AuthedAdminClubsRoute
  '/_authed/clubs/$clubId': typeof AuthedClubsClubIdRouteWithChildren
  '/_authed/clubs/new': typeof AuthedClubsNewRoute
  '/_authed/events/$eventId': typeof AuthedEventsEventIdRouteWithChildren
  '/_authed/events/new': typeof AuthedEventsNewRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/clubs/': typeof AuthedClubsIndexRoute
  '/_authed/events/': typeof AuthedEventsIndexRoute
  '/_authed/schools/': typeof AuthedSchoolsIndexRoute
  '/_authed/clubs/$clubId/board': typeof AuthedClubsClubIdBoardRoute
  '/_authed/events/$eventId/board': typeof AuthedEventsEventIdBoardRoute
  '/_authed/events/$eventId/chat': typeof AuthedEventsEventIdChatRoute
  '/_authed/events/$eventId/wizard': typeof AuthedEventsEventIdWizardRoute
  '/_authed/schools/$schoolId/board': typeof AuthedSchoolsSchoolIdBoardRoute
  '/_authed/clubs/$clubId/': typeof AuthedClubsClubIdIndexRoute
  '/_authed/events/$eventId/': typeof AuthedEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/clubs'
    | '/events'
    | '/profile'
    | '/schools'
    | '/admin/clubs'
    | '/clubs/$clubId'
    | '/clubs/new'
    | '/events/$eventId'
    | '/events/new'
    | '/admin/'
    | '/clubs/'
    | '/events/'
    | '/schools/'
    | '/clubs/$clubId/board'
    | '/events/$eventId/board'
    | '/events/$eventId/chat'
    | '/events/$eventId/wizard'
    | '/schools/$schoolId/board'
    | '/clubs/$clubId/'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/profile'
    | '/admin/clubs'
    | '/clubs/new'
    | '/events/new'
    | '/admin'
    | '/clubs'
    | '/events'
    | '/schools'
    | '/clubs/$clubId/board'
    | '/events/$eventId/board'
    | '/events/$eventId/chat'
    | '/events/$eventId/wizard'
    | '/schools/$schoolId/board'
    | '/clubs/$clubId'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/clubs'
    | '/_authed/events'
    | '/_authed/profile'
    | '/_authed/schools'
    | '/_authed/admin/clubs'
    | '/_authed/clubs/$clubId'
    | '/_authed/clubs/new'
    | '/_authed/events/$eventId'
    | '/_authed/events/new'
    | '/_authed/admin/'
    | '/_authed/clubs/'
    | '/_authed/events/'
    | '/_authed/schools/'
    | '/_authed/clubs/$clubId/board'
    | '/_authed/events/$eventId/board'
    | '/_authed/events/$eventId/chat'
    | '/_authed/events/$eventId/wizard'
    | '/_authed/schools/$schoolId/board'
    | '/_authed/clubs/$clubId/'
    | '/_authed/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/schools': {
      id: '/_authed/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthedSchoolsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/events': {
      id: '/_authed/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthedEventsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clubs': {
      id: '/_authed/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof AuthedClubsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schools/': {
      id: '/_authed/schools/'
      path: '/'
      fullPath: '/schools/'
      preLoaderRoute: typeof AuthedSchoolsIndexRouteImport
      parentRoute: typeof AuthedSchoolsRoute
    }
    '/_authed/events/': {
      id: '/_authed/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthedEventsIndexRouteImport
      parentRoute: typeof AuthedEventsRoute
    }
    '/_authed/clubs/': {
      id: '/_authed/clubs/'
      path: '/'
      fullPath: '/clubs/'
      preLoaderRoute: typeof AuthedClubsIndexRouteImport
      parentRoute: typeof AuthedClubsRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/events/new': {
      id: '/_authed/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthedEventsNewRouteImport
      parentRoute: typeof AuthedEventsRoute
    }
    '/_authed/events/$eventId': {
      id: '/_authed/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthedEventsEventIdRouteImport
      parentRoute: typeof AuthedEventsRoute
    }
    '/_authed/clubs/new': {
      id: '/_authed/clubs/new'
      path: '/new'
      fullPath: '/clubs/new'
      preLoaderRoute: typeof AuthedClubsNewRouteImport
      parentRoute: typeof AuthedClubsRoute
    }
    '/_authed/clubs/$clubId': {
      id: '/_authed/clubs/$clubId'
      path: '/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof AuthedClubsClubIdRouteImport
      parentRoute: typeof AuthedClubsRoute
    }
    '/_authed/admin/clubs': {
      id: '/_authed/admin/clubs'
      path: '/clubs'
      fullPath: '/admin/clubs'
      preLoaderRoute: typeof AuthedAdminClubsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/events/$eventId/': {
      id: '/_authed/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthedEventsEventIdIndexRouteImport
      parentRoute: typeof AuthedEventsEventIdRoute
    }
    '/_authed/clubs/$clubId/': {
      id: '/_authed/clubs/$clubId/'
      path: '/'
      fullPath: '/clubs/$clubId/'
      preLoaderRoute: typeof AuthedClubsClubIdIndexRouteImport
      parentRoute: typeof AuthedClubsClubIdRoute
    }
    '/_authed/schools/$schoolId/board': {
      id: '/_authed/schools/$schoolId/board'
      path: '/$schoolId/board'
      fullPath: '/schools/$schoolId/board'
      preLoaderRoute: typeof AuthedSchoolsSchoolIdBoardRouteImport
      parentRoute: typeof AuthedSchoolsRoute
    }
    '/_authed/events/$eventId/wizard': {
      id: '/_authed/events/$eventId/wizard'
      path: '/wizard'
      fullPath: '/events/$eventId/wizard'
      preLoaderRoute: typeof AuthedEventsEventIdWizardRouteImport
      parentRoute: typeof AuthedEventsEventIdRoute
    }
    '/_authed/events/$eventId/chat': {
      id: '/_authed/events/$eventId/chat'
      path: '/chat'
      fullPath: '/events/$eventId/chat'
      preLoaderRoute: typeof AuthedEventsEventIdChatRouteImport
      parentRoute: typeof AuthedEventsEventIdRoute
    }
    '/_authed/events/$eventId/board': {
      id: '/_authed/events/$eventId/board'
      path: '/board'
      fullPath: '/events/$eventId/board'
      preLoaderRoute: typeof AuthedEventsEventIdBoardRouteImport
      parentRoute: typeof AuthedEventsEventIdRoute
    }
    '/_authed/clubs/$clubId/board': {
      id: '/_authed/clubs/$clubId/board'
      path: '/board'
      fullPath: '/clubs/$clubId/board'
      preLoaderRoute: typeof AuthedClubsClubIdBoardRouteImport
      parentRoute: typeof AuthedClubsClubIdRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminClubsRoute: typeof AuthedAdminClubsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminClubsRoute: AuthedAdminClubsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedClubsClubIdRouteChildren {
  AuthedClubsClubIdBoardRoute: typeof AuthedClubsClubIdBoardRoute
  AuthedClubsClubIdIndexRoute: typeof AuthedClubsClubIdIndexRoute
}

const AuthedClubsClubIdRouteChildren: AuthedClubsClubIdRouteChildren = {
  AuthedClubsClubIdBoardRoute: AuthedClubsClubIdBoardRoute,
  AuthedClubsClubIdIndexRoute: AuthedClubsClubIdIndexRoute,
}

const AuthedClubsClubIdRouteWithChildren =
  AuthedClubsClubIdRoute._addFileChildren(AuthedClubsClubIdRouteChildren)

interface AuthedClubsRouteChildren {
  AuthedClubsClubIdRoute: typeof AuthedClubsClubIdRouteWithChildren
  AuthedClubsNewRoute: typeof AuthedClubsNewRoute
  AuthedClubsIndexRoute: typeof AuthedClubsIndexRoute
}

const AuthedClubsRouteChildren: AuthedClubsRouteChildren = {
  AuthedClubsClubIdRoute: AuthedClubsClubIdRouteWithChildren,
  AuthedClubsNewRoute: AuthedClubsNewRoute,
  AuthedClubsIndexRoute: AuthedClubsIndexRoute,
}

const AuthedClubsRouteWithChildren = AuthedClubsRoute._addFileChildren(
  AuthedClubsRouteChildren,
)

interface AuthedEventsEventIdRouteChildren {
  AuthedEventsEventIdBoardRoute: typeof AuthedEventsEventIdBoardRoute
  AuthedEventsEventIdChatRoute: typeof AuthedEventsEventIdChatRoute
  AuthedEventsEventIdWizardRoute: typeof AuthedEventsEventIdWizardRoute
  AuthedEventsEventIdIndexRoute: typeof AuthedEventsEventIdIndexRoute
}

const AuthedEventsEventIdRouteChildren: AuthedEventsEventIdRouteChildren = {
  AuthedEventsEventIdBoardRoute: AuthedEventsEventIdBoardRoute,
  AuthedEventsEventIdChatRoute: AuthedEventsEventIdChatRoute,
  AuthedEventsEventIdWizardRoute: AuthedEventsEventIdWizardRoute,
  AuthedEventsEventIdIndexRoute: AuthedEventsEventIdIndexRoute,
}

const AuthedEventsEventIdRouteWithChildren =
  AuthedEventsEventIdRoute._addFileChildren(AuthedEventsEventIdRouteChildren)

interface AuthedEventsRouteChildren {
  AuthedEventsEventIdRoute: typeof AuthedEventsEventIdRouteWithChildren
  AuthedEventsNewRoute: typeof AuthedEventsNewRoute
  AuthedEventsIndexRoute: typeof AuthedEventsIndexRoute
}

const AuthedEventsRouteChildren: AuthedEventsRouteChildren = {
  AuthedEventsEventIdRoute: AuthedEventsEventIdRouteWithChildren,
  AuthedEventsNewRoute: AuthedEventsNewRoute,
  AuthedEventsIndexRoute: AuthedEventsIndexRoute,
}

const AuthedEventsRouteWithChildren = AuthedEventsRoute._addFileChildren(
  AuthedEventsRouteChildren,
)

interface AuthedSchoolsRouteChildren {
  AuthedSchoolsIndexRoute: typeof AuthedSchoolsIndexRoute
  AuthedSchoolsSchoolIdBoardRoute: typeof AuthedSchoolsSchoolIdBoardRoute
}

const AuthedSchoolsRouteChildren: AuthedSchoolsRouteChildren = {
  AuthedSchoolsIndexRoute: AuthedSchoolsIndexRoute,
  AuthedSchoolsSchoolIdBoardRoute: AuthedSchoolsSchoolIdBoardRoute,
}

const AuthedSchoolsRouteWithChildren = AuthedSchoolsRoute._addFileChildren(
  AuthedSchoolsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedClubsRoute: typeof AuthedClubsRouteWithChildren
  AuthedEventsRoute: typeof AuthedEventsRouteWithChildren
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedSchoolsRoute: typeof AuthedSchoolsRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedClubsRoute: AuthedClubsRouteWithChildren,
  AuthedEventsRoute: AuthedEventsRouteWithChildren,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedSchoolsRoute: AuthedSchoolsRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
