/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Firebase 토큰 로그인
         * @description Firebase ID Token을 받아 검증하고 자체 JWT 발급
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example eyJhbGciOiJSUzI1NiIs... */
                        firebaseIdToken: string;
                    };
                };
            };
            responses: {
                /** @description 로그인 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken?: string;
                            isNewUser?: boolean;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 최초 회원가입 (학교/역할 선택) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname: string;
                        /** Format: int64 */
                        schoolId: number;
                        personalRole?: components["schemas"]["PersonalRole"];
                        bio?: string;
                    };
                };
            };
            responses: {
                /** @description 가입 완료 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 프로필 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 내 프로필 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname?: string;
                        profileImage?: string;
                        personalRole?: components["schemas"]["PersonalRole"];
                        bio?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/schools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 학교 목록 (회원가입 시 사용) */
        get: {
            parameters: {
                query?: {
                    region?: components["schemas"]["Region"];
                    whitelistedOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["School"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 학교 상세 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["School"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/{id}/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 교내 시설 목록 */
        get: {
            parameters: {
                query?: {
                    facilityType?: components["schemas"]["FacilityType"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchoolFacility"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 동아리 목록 */
        get: {
            parameters: {
                query?: {
                    schoolId?: number;
                    category?: components["schemas"]["ClubCategory"];
                    status?: components["schemas"]["ClubStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Club"][];
                    };
                };
            };
        };
        put?: never;
        /** 동아리 생성 신청 (PENDING) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        schoolId: number;
                        name: string;
                        category?: components["schemas"]["ClubCategory"];
                        description?: string;
                        logoImage?: string;
                        evidenceUrl?: string;
                    };
                };
            };
            responses: {
                /** @description 신청 완료 (status=PENDING) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Club"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clubs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 동아리 상세 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Club"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 동아리 정보 수정 (회장 전용) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        description?: string;
                        logoImage?: string;
                        evidenceUrl?: string;
                        category?: components["schemas"]["ClubCategory"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Club"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/clubs/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 동아리 승인 (SUPER_ADMIN) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Club"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/clubs/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 동아리 거절 (SUPER_ADMIN) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rejectReason: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Club"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/clubs/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 초대코드로 동아리 가입 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        inviteCode: string;
                    };
                };
            };
            responses: {
                /** @description 가입 완료 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClubMember"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clubs/{clubId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 동아리 부원 목록 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clubId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClubMember"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clubs/{clubId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 부원 강퇴 또는 탈퇴 (status=LEFT) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clubId: number;
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 행사 목록 */
        get: {
            parameters: {
                query?: {
                    type?: components["schemas"]["EventType"];
                    status?: components["schemas"]["EventStatus"];
                    hostClubId?: number;
                    category?: components["schemas"]["EventCategory"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"][];
                    };
                };
            };
        };
        put?: never;
        /** 행사 생성 (DRAFT) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        type: components["schemas"]["EventType"];
                        /** Format: int64 */
                        hostClubId: number;
                        /** Format: int64 */
                        partnerClubId?: number;
                        title: string;
                        category?: components["schemas"]["EventCategory"];
                        description?: string;
                        format?: string;
                        proposalMessage?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 행사 상세 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 행사 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** 행사 수정 (장소/일정/모집정보) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/events/{id}/ai/step1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gemini Step 1 정제 (제목/카테고리/설명 보강) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/ai/step2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gemini Step 2 정제 (장소/공지글/모집정보) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 연합 행사 → partner 검토 요청 (PARTNER_REVIEW) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** partner 측 승인 (APPROVED) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/events/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** partner 측 거절 (REJECTED) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rejectReason: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/events/{id}/recruiting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 모집 시작 (RECRUITING) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/events/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 모집 마감 (CLOSED) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/events/{eventId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 행사 참여자 목록 */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["ParticipantStatus"];
                };
                header?: never;
                path: {
                    eventId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventParticipant"][];
                    };
                };
            };
        };
        put?: never;
        /** 행사 참여 신청 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        participatingRole?: components["schemas"]["PersonalRole"];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventParticipant"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participants/{participantId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 참여자 승인 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: number;
                    participantId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/events/{eventId}/participants/{participantId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 참여자 거절 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: number;
                    participantId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시글 목록 (행사 게시판) */
        get: {
            parameters: {
                query: {
                    boardType: components["schemas"]["BoardType"];
                    targetId: number;
                    category?: components["schemas"]["PostCategory"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Post"][];
                    };
                };
            };
        };
        put?: never;
        /** 게시글 작성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        boardType: components["schemas"]["BoardType"];
                        /** Format: int64 */
                        targetId: number;
                        category?: components["schemas"]["PostCategory"];
                        title: string;
                        content: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Post"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시글 상세 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Post"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 게시글 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** 게시글 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        content?: string;
                        category?: components["schemas"]["PostCategory"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/posts/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 댓글 목록 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    postId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"][];
                    };
                };
            };
        };
        put?: never;
        /** 댓글 작성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    postId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 댓글 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/chat-room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 행사 채팅방 조회 (event당 1개) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatRoom"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat-rooms/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 채팅방 입장 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatRoomMember"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat-rooms/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 메시지 목록 (페이지네이션) */
        get: {
            parameters: {
                query?: {
                    before?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatMessage"][];
                    };
                };
            };
        };
        put?: never;
        /** 메시지 전송 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                        messageType?: components["schemas"]["MessageType"];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatMessage"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat-rooms/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 마지막 읽은 시각 업데이트 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/chat-rooms/{id}/bot/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 봇 발화 트리거 (welcome / reminder 등) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type: "BOT_WELCOME" | "BOT_REMINDER";
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatMessage"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 알림 목록 */
        get: {
            parameters: {
                query?: {
                    unreadOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 알림 읽음 처리 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 전체 읽음 처리 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Region: "GYEONGIN" | "SEOUL" | "OTHER";
        /** @enum {string} */
        CampusType: "MAIN" | "BRANCH";
        /** @enum {string} */
        UserRole: "SUPER_ADMIN" | "PRESIDENT" | "MEMBER";
        /** @enum {string} */
        PersonalRole: "DESIGNER" | "FRONTEND" | "BACKEND" | "PLANNER" | "IOS" | "ANDROID";
        /** @enum {string} */
        AuthProvider: "GOOGLE";
        /** @enum {string} */
        FacilityType: "LECTURE_ROOM" | "AUDITORIUM" | "STUDY_ROOM";
        /** @enum {string} */
        ClubCategory: "DEV" | "DESIGN" | "STARTUP" | "ART" | "SPORTS";
        /** @enum {string} */
        ClubStatus: "PENDING" | "APPROVED" | "REJECTED";
        /** @enum {string} */
        ClubMemberRole: "PRESIDENT" | "MEMBER";
        /** @enum {string} */
        ClubMemberStatus: "APPROVED" | "LEFT";
        /** @enum {string} */
        EventType: "INTRA_CLUB" | "INTER_CLUB";
        /** @enum {string} */
        EventCategory: "HACKATHON" | "MEETUP" | "STUDY" | "FESTIVAL" | "WORKSHOP";
        /** @enum {string} */
        EventStatus: "DRAFT" | "PARTNER_REVIEW" | "APPROVED" | "REJECTED" | "RECRUITING" | "CLOSED";
        /** @enum {string} */
        ParticipantStatus: "PENDING" | "APPROVED" | "REJECTED";
        /** @enum {string} */
        BoardType: "EVENT" | "SCHOOL" | "CLUB";
        /** @enum {string} */
        PostCategory: "NOTICE" | "SCHEDULE" | "TEAM_BUILDING" | "QNA" | "RESOURCE";
        /** @enum {string} */
        SenderType: "USER" | "BOT";
        /** @enum {string} */
        MessageType: "TEXT" | "SYSTEM" | "BOT_CARD";
        /** @enum {string} */
        BotPersona: "HACKATHON_BOT" | "MEETUP_BOT" | "STUDY_BOT";
        /** @enum {string} */
        NotificationType: "CLUB_APPROVED" | "ALLIANCE_REQUEST" | "EVENT_APPROVED" | "NEW_MESSAGE" | "BOT_REMINDER";
        /** @enum {string} */
        AiType: "EVENT_STEP1" | "EVENT_STEP2_INTRA" | "EVENT_STEP2_INTER" | "BOT_WELCOME" | "BOT_REMINDER";
        User: {
            /** Format: int64 */
            id?: number;
            firebaseUid?: string;
            authProvider?: components["schemas"]["AuthProvider"];
            email?: string;
            nickname?: string;
            profileImage?: string;
            /** Format: int64 */
            schoolId?: number;
            personalRole?: components["schemas"]["PersonalRole"];
            bio?: string;
            role?: components["schemas"]["UserRole"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        School: {
            /** Format: int64 */
            id?: number;
            name?: string;
            emailDomain?: string;
            region?: components["schemas"]["Region"];
            campusType?: components["schemas"]["CampusType"];
            lat?: number;
            lng?: number;
            mascotImage?: string;
            isWhitelisted?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        SchoolFacility: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            schoolId?: number;
            name?: string;
            facilityType?: components["schemas"]["FacilityType"];
            capacity?: number;
            lat?: number;
            lng?: number;
        };
        Club: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            schoolId?: number;
            /** Format: int64 */
            presidentUserId?: number;
            name?: string;
            category?: components["schemas"]["ClubCategory"];
            description?: string;
            inviteCode?: string;
            logoImage?: string;
            evidenceUrl?: string;
            status?: components["schemas"]["ClubStatus"];
            /** Format: int64 */
            approvedByUserId?: number;
            /** Format: date-time */
            approvedAt?: string;
            rejectReason?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ClubMember: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            clubId?: number;
            /** Format: int64 */
            userId?: number;
            memberRole?: components["schemas"]["ClubMemberRole"];
            status?: components["schemas"]["ClubMemberStatus"];
            /** Format: date-time */
            joinedAt?: string;
        };
        Event: {
            /** Format: int64 */
            id?: number;
            type?: components["schemas"]["EventType"];
            /** Format: int64 */
            hostClubId?: number;
            /** Format: int64 */
            partnerClubId?: number;
            title?: string;
            category?: components["schemas"]["EventCategory"];
            description?: string;
            format?: string;
            step1Data?: {
                [key: string]: unknown;
            };
            step2Data?: {
                [key: string]: unknown;
            };
            locationName?: string;
            locationAddress?: string;
            locationLat?: number;
            locationLng?: number;
            placeId?: string;
            /** Format: int64 */
            facilityId?: number;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            /** Format: date-time */
            recruitDeadline?: string;
            maxParticipants?: number;
            status?: components["schemas"]["EventStatus"];
            hostApproved?: boolean;
            partnerApproved?: boolean;
            proposalMessage?: string;
            rejectReason?: string;
            /** Format: date-time */
            partnerRespondedAt?: string;
            /** Format: int64 */
            createdByUserId?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        EventUpdateRequest: {
            title?: string;
            category?: components["schemas"]["EventCategory"];
            description?: string;
            format?: string;
            locationName?: string;
            locationAddress?: string;
            locationLat?: number;
            locationLng?: number;
            placeId?: string;
            /** Format: int64 */
            facilityId?: number;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            /** Format: date-time */
            recruitDeadline?: string;
            maxParticipants?: number;
        };
        EventParticipant: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            eventId?: number;
            /** Format: int64 */
            userId?: number;
            participatingRole?: components["schemas"]["PersonalRole"];
            status?: components["schemas"]["ParticipantStatus"];
            /** Format: date-time */
            appliedAt?: string;
            /** Format: date-time */
            respondedAt?: string;
        };
        Post: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            authorId?: number;
            boardType?: components["schemas"]["BoardType"];
            /** Format: int64 */
            targetId?: number;
            category?: components["schemas"]["PostCategory"];
            isOfficialNotice?: boolean;
            title?: string;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Comment: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            postId?: number;
            /** Format: int64 */
            authorId?: number;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ChatRoom: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            eventId?: number;
            botPersona?: components["schemas"]["BotPersona"];
            /** Format: date-time */
            createdAt?: string;
        };
        ChatRoomMember: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            chatRoomId?: number;
            /** Format: int64 */
            userId?: number;
            /** Format: date-time */
            joinedAt?: string;
            /** Format: date-time */
            lastReadAt?: string;
        };
        ChatMessage: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            chatRoomId?: number;
            senderType?: components["schemas"]["SenderType"];
            /** Format: int64 */
            senderUserId?: number;
            botPersona?: components["schemas"]["BotPersona"];
            content?: string;
            messageType?: components["schemas"]["MessageType"];
            /** Format: date-time */
            createdAt?: string;
        };
        Notification: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            type?: components["schemas"]["NotificationType"];
            /** @enum {string} */
            targetType?: "EVENT" | "CLUB" | "CHAT_ROOM";
            /** Format: int64 */
            targetId?: number;
            title?: string;
            message?: string;
            isRead?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: {
        IdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
